nodeLinker: node-modules

enableGlobalCache: true

packageExtensions:
  '@calcu-bot/shared@*':
    dependencies:
      typescript: '*'
  '@calcu-bot/math-lib@*':
    dependencies:
      typescript: '*'