# Use the official Node.js image as a base
FROM node:22

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and yarn.lock (or package-lock.json) to the working directory
COPY package.json ./

# Install dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of your application code to the working directory
COPY . .

# Build the TypeScript code
RUN yarn build

# Expose the port your app runs on
EXPOSE 3000

# Command to run your application
CMD ["node", "dist/index.js"] 